### ISSUE TITLE
Different LV ellipsoid parametrization compared to legacy code

### ISSUE THREAD

**Issue by dajuno** [ComputationalPhysiology/cardiac-geometriesx#41]
Hello,

thank you for your work!

I noticed that the LV ellipsoid parametrization changed a little in the current version, compared to the legacy code:

https://github.com/ComputationalPhysiology/cardiac-geometriesx/blob/32aa12b95d887341324f09882e4b636d8a8d65e8/src/cardiac_geometries/fibers/lv_ellipsoid.py#L38-L39

vs

https://github.com/ComputationalPhysiology/cardiac-geometries/blob/05fa16c53909d108e07b802380e881d57ea02103/src/cardiac_geometries/fibers/_lv_ellipsoid.py#L125-L126

This change seems to affect the result. Is one of the formulations wrong?

Thank you!

**Comment by dajuno** [comment]
More precisely, the change was introduced with https://github.com/ComputationalPhysiology/cardiac-geometriesx/commit/5141d3febab8631329a1039b1fcf711255234c67

**Comment by finsberg** [comment]
Hi @dajuno. Thanks for reporting this. The legacy version is correct. I will update this version asap. Thanks

**Comment by finsberg** [comment]
Fixed in #42
